nT_string = "GACACTATTGTTCGGTATCCCAAGGTTCGGCTACCCTCGCTCACCACACCCGATGCAATAGGTCGGGCTAACCTCCGCTACTTTAAGACTGGCCAACGACAGGCCTGTCAGTGTAAATGCACTTGCGAGCAGTTCTCAGAAGCTTGTCAAAAGTACACGGCTCCTTGCTTTACCGTTGAGCTTCGGTCGGTAACGTGCTCCATAGACGTACAAGGAGTGTGAGTGGGCTGGGCTTAGCCCTGCCGACATATATACCAAGTTGTTCCTCAGTGGGGGTTTTACATACGCTCGGATGCGCTTGCCAGGACTATTAATCAACTTGAGCGGGATCTCGTTCTAGCCTAGAAGCCATAGAAGACTTTAGTCATCCCCTTTCTGACAGCAATCCCTTACAGTGTTCTCAAGCCTCGTTACGGAGTAAAGGACCTGAACGAAAGGGCCTCGGCACAGTCTTTAATGGTGTCAATGTCGGGGCTGCTACCGTCAATACAGTCAGACTCCGGATACAATGGCAATCCTATCTCTTGCGCCTATATACAACGTATCTAGCCATTTTGAGGAAACGCTCCTCGTATTATGGCTAACTATAACACATTGTGGAAAAGCTTCATAGAAATACGTATGTGCAGAGGACGGTTATGACCGTTCCATGGCCTTACGACCGTGAACCCTTCTATGCGGTGATCCTCGCTGTTTAGATAACGAAAATTATTCTCTGAACTATCCAGTATGCCTCTGTTCGTTTCGGAGTGGCTCCGACCATGACACCTGAAGGAATTGAAGAAGCTTGGAGTTGTCTTTCATTCGGAGTCAATTAATACAAGCGAAGCTGGAGGTAACGCCCGTCCTTTGACGGGACGTCGAGAGCGGCGAAAGCGTTACCATGTACGGTAAAGCGCACGTGATTCACGCAGGAAGGATTGTACAGGCAGCTTTCACGCTCAAGCAGAGACGACTTCTCCGGTTACAGCGCACGGTTTCGCGAAGCTGACCTCGA"


# Counts the instances of each nucleotide in the given DNA string
def countNt(DNAString):
  counts = {
    'A': 0,
    'C': 0,
    'G': 0,
    'T': 0,
  }

  for letter in DNAString:
    counts[letter] = counts[letter] + 1

  print(counts['A'], counts['C'], counts['G'], counts['T'])
  return


countNt(nT_string)
