# Given a DNA strand, return the reverse complement (its pair strand with complementary nt in reverse order)

# eg) Given "GTCA" -> "TGAC"

DNA_str1 = "GCGGAAGGGTGCACACTATAAATGCTAACTAATGAAGATCTTCATGCAGGCACTTAATACAATGTCGACAAAACCCTAACGCTCCCGCCGTCTGCAACTCCCAAAGGTCATGATAGAAGCCCCACATTTTTGTTAACGGCAGGAGTTTTCACTACCCGCATTGGCGTTGTGGAGGCAAAGAGGTGAGATGCGGACAGGCTATGGCCTAAGTCACACGGAATTTGCGTGTTGTAAACGGTTCCGTGCCGATTCGTTATATCTAGCAAATCCAGAAAGGACGTTATGTGCCTCTGACGTGATGCAGAACCCGGAGGGCAAGGTGTGGCGAATGGATTGAGCATTACTCAGTCTGTCTCACCAGGAGCTTTCCATGCCCGTTGAATGCACAGGTCGACAAGGACGCTTCGGCTCCAAATCAGTCTGTGGCTACTTGGAAGCTAGTCACCCTGCCATGGTTCTGAGTTTGTACTTGTTTTAACACGCTACAGACAGGAGCCCTGCTCGGTAGAATTGAGGTTTGCGCCCTCCATGCGCGGATCTCTCGAGCCACGCATCTTATCGTTAGCGCATAGAGTCCGTAAGTCCAGACGCACGCCCCGCCCCAAATCCCAGACCTACGACGCCCGTGGTATGCATGAAACGGCCTGGACTCGCAACTCCTGGGGGGTAGCGGGCTTCCTATGTAGCGAATAGGGAAAGGAACCTTCGTTGGCCACTTAACGGGTTTAGGTACCGCTCAATGTTCTCTTGGTCTTAGTAACGTAAGCCACTTCCTCTGCCGGCGACTTAAGATGACAATCTTTGCAGAGCGACGTCGCTCTGTAAAGTAG"

complements = {
  "G": "C",
  "C": "G",
  "A": "T",
  "T": "A",
}

reverse = DNA_str1[::-1] # reverse the string

complement = ""

for nt in reverse:
  complement += complements[nt]

print(complement)